### PR TITLE
Collapsed Property to hide the palette initially

### PR DESCRIPTION
**Pull request by deen13**
I've added a collapsed property to initially hide the palette. This is needed in my use-case because it's rendered inside of a v-card.

### CODE REVIEW

**Comment by rkunev** [comment]
Hi, thank you for the contribution! Addition looks good & clean, but it conflicts a little bit in this case:
```vue
<color-picker variant="persistent" :collapsed="true" v-bind="color" @input="onInput" />
```
If the picker is "persistent" and it shouldn't collapse, but also should be initially collapsed, what would be the expected behavior (e.g. clicking on the color well in the middle)? I'm open for suggestions here.

Side note - wouldn't it also make more sense to name the prop `initiallyCollapsed`? I'm okay with longer, but more descriptive/accurate names.

**Comment by deen13** [comment]
Hey @rkunev, 

i applied your suggestion to the property name. 👍

**Comment by deen13** [comment]
Do you think that a third variant called collapsible-and-collect or something like that would make sense? Im absolutely with you that my changes would be conflicting otherwise.

**Comment by rkunev** [comment]
You know what, let's keep things simple. 
```vue
<color-picker variant="persistent" :initiallyCollapsed="true" />
```
The above usage is either by accident/mistake or it's someone trying to break things. If someone uses this we can log a warning `Incorrect config: using variant="persistent" and :initiallyCollapsed="true" at the same time is not supported.`.

**Comment by deen13** [comment]
I would love to unit test the computed property `propertiesAreConflicting` but i have no clue how 😭

**Comment by rkunev** [comment]
One way we can achieve this is by using a `hasConflictingProps()` method that will apply the validation logic, conditionally log the warning and return a boolean whether the validation passed. The other way is to have a `logWarning(message)` method that will be called when validation didn't succeed and to use a stub (`jest.fn()`) to check if the `logWarning()` method was called.

Either way, the computed property is probably not needed since we're going to use it just once, when the component mounts.

**Comment by deen13** [comment]
image

**Comment by rkunev** [comment]
Sure thing! I'll do it when I get back to my laptop later today. I'll let you know when the new version is released to NPM as well. 

Thanks again!

**Comment by rkunev** [comment]
@deen13 `2.1.0` is out & available on [NPM](https://www.npmjs.com/package/@radial-color-picker/vue-color-picker)! Contributors list has been updated as well  🎉

**Comment by deen13** [comment]
Thanks! Keep up the great work! 🥇

**Pull request merged**
